version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 881490090991.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t candid-fox-repo .
      - docker tag candid-fox-repo:latest 881490090991.dkr.ecr.ap-south-1.amazonaws.com/candid-fox-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 881490090991.dkr.ecr.ap-south-1.amazonaws.com/candid-fox-repo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"candid-fox-container","imageUri":"%s"}]' 881490090991.dkr.ecr.ap-south-1.amazonaws.com/candid-fox-repo:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
